name:                mock-time
version:             0.1.0
synopsis:            Mock time in tests
description:         Allows to mock out Data.Time.getCurrentTime and Control.Concrurent.threadDelay
homepage:            https://github.com/luntain/error-or-bundle/blob/master/mock-time#readme
license:             BSD3
maintainer:          kamil@dworakowski.name
author:              Kamil Dworakowski
copyright:           2020 Kamil Dworakowski
category:            Test
extra-source-files:
- README.md

tested-with: GHC==8.0.1, GHC==8.2.2, GHC==8.8.1, GHC==8.8.3, GHC==8.10.2

dependencies:
  - base >= 4.7 && < 5
  - time
  - stm
  - mtl
  - exceptions
  - resourcet
  - primitive
  - unliftio-core
  - error-or

library:
    source-dirs:      src

tests:
  my-test-suite:
    source-dirs: tests
    main: Tests.hs
    dependencies:
    - mock-time
    - error-or-utils
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - QuickCheck
    - inbox
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
