name:                inbox
version:             0.2.0
synopsis:            Inbox for asychronous messages
description:         Facilitates testing of asynchronous behavior
homepage:            https://github.com/luntain/error-or-bundle/blob/master/inbox#readme
license:             BSD3
author:              Kamil Dworakowski
maintainer:          kamil@dworakowski.name
copyright:           2020 Kamil Dworakowski
category:            Testing
extra-source-files:
- README.md

tested-with: GHC==8.0.1, GHC==8.2.2, GHC==8.8.1, GHC==8.8.3, GHC==8.10.2

dependencies:
  - base >= 4.7 && < 5
  - text
  - async
  - error-or >= 0.2.0.0
  - time

library:
  source-dirs:      src
  ghc-options: -Wall -fno-warn-name-shadowing
